services:
  gnome-docker:
    container_name: gnome-docker
    tty: true
    build: .

    # Use systemd
    cgroup: host
    volumes:
      # Systemd requirements
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/fs/cgroup/system.slice:/sys/fs/cgroup/system.slice:rw
      - ./machine-id:/etc/machine-id:rw

      - /tmp/.X11-unix/X1001:/host/X

    # Remote
    ports:
      # for rdp
      - 3389:3389
      # for vnc
      - 5900:5900

    # For gpu
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    devices:
      - /dev/dri/renderD128
      - /dev/kfd
      - /dev/fb0
