services:
  gnome-docker:
    extends:
      file: gnome-docker.yml
      service: gnome-docker
    container_name: gnome-docker

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      # for rdp
      - 3389:3389
      # for vnc
      - 5900:5900

    # For gpu
    security_opt:
      - seccomp:unconfined
    group_add:
      - video
    devices:
      - /dev/dri/renderD128
      - /dev/kfd
      - /dev/fb0
