services:
  gnome-docker:
    container_name: gnome-docker
    hostname: gnome-docker
    build: .

    environment:
      VNC_OPTION: -SecurityTypes=None -rfbunixpath /host/vncsocket -rfbport -1
      RDP_ENABLE: false
      ROOTMODE: false

    # For systemd
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cgroup: host
    volumes:
      # Systemd requirements
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/fs/cgroup/system.slice:/sys/fs/cgroup/system.slice:rw
      # For vnc unix socket, machine-id
      - ./host:/host:rw
      - ./host/home:/home/gnome

    # Remote
    # ports:
      # for rdp
      # - 3389:3389
      # for vnc
      # - 5900:5900

    # For gpu
    group_add:
      - video
      - render
    devices:
      - /dev/dri/renderD128
      - /dev/kfd
