services:
  gnome-docker:
    tty: true
    build: .

    # Use systemd
    cgroup: host
    volumes:
      # Systemd requirements
      - type: tmpfs
        target: /tmp
      - type: tmpfs
        target: /run
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /sys/fs/cgroup/system.slice:/sys/fs/cgroup/system.slice:rw
      - ./machine-id:/etc/machine-id:rw

